# Generated by Django 5.1.1 on 2024-10-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="status",
        ),
        migrations.AddField(
            model_name="room",
            name="available_rooms",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="room",
            name="total_rooms",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(max_length=100),
        ),
    ]
